# Generated by Django 4.2.7 on 2023-11-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_item_discount_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
