# Generated by Django 4.2.7 on 2023-11-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon_order_refund_payment_order_payment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
