# Generated by Django 4.2.7 on 2023-11-12 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1, null=True, verbose_name='Address Type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='stree_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stree Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip Code'),
        ),
    ]
