# Generated by Django 4.2.7 on 2023-11-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_address',
        ),
    ]
