# Generated by Django 4.2.7 on 2023-11-12 10:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_address_type_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True, verbose_name='Country'),
        ),
    ]
